GET http://localhost:3000/users HTTP/1.1

###

GET http://localhost:3000/user/44f06b90-b9c0-40ef-9ebf-1a4994d84e6c HTTP/1.1

###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "nome": "Matheus alves",
    "email": "matheus@gmail.com"
}
###

POST http://localhost:3000/todos HTTP/1.1
content-type: application/json
x-user-id: ea521ab5-7b62-4de8-805d-dfc5ea5b0513

{
    "title": "Minha tarefa de número 1"
}

###

POST http://localhost:3000/checkout HTTP/1.1
x-user-id: ea521ab5-7b62-4de8-805d-dfc5ea5b0513

